# Generated by Django 5.2.1 on 2025-05-30 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_useraddress_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraddress',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='useraddress',
            name='street',
        ),
    ]
