# Generated by Django 5.2.1 on 2025-06-07 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_order_razorpay_order_id_order_razorpay_payment_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at']},
        ),
    ]
