# Generated by Django 5.2.1 on 2025-06-11 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_passwordresetotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Smartphones', 'Smartphones'), ('Laptops', 'Laptops'), ('Accessories', 'Accessories'), ('Smart TVs', 'Smart TVs')], default='Accessories', max_length=100),
        ),
    ]
