# Generated by Django 5.2.1 on 2025-06-12 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_product_rating_product_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Smartphones', 'Smartphones'), ('Laptops', 'Laptops'), ('Smart TVs', 'Smart TVs'), ('Smart Watches & Wearables', 'Smart Watches & Wearables'), ('Audio Devices', 'Audio Devices'), ('Cameras & Photography', 'Cameras & Photography'), ('Smart Home Appliances', 'Smart Home Appliances')], default='Smartphones', max_length=100),
        ),
    ]
