# Generated by Django 5.2.1 on 2025-06-12 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Smartphones', 'Smartphones'), ('Laptops', 'Laptops'), ('Smart TVs', 'Smart TVs'), ('Smart Watches & Wearables', 'Smart Watches & Wearables'), ('Audio Devices', 'Audio Devices'), ('Cameras & Photography', 'Cameras & Photography'), ('Smart Home Appliances', 'Smart Home Appliances'), ('Printers & Mouse', 'Printers & Mouse'), ('Chargers & Power Banks', 'Chargers & Power Banks')], default='Smartphones', max_length=100),
        ),
    ]
