# Generated by Django 5.2.1 on 2025-06-13 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_product_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(choices=[('Apple', 'Apple'), ('Samsung', 'Samsung'), ('OnePlus', 'OnePlus'), ('Xiaomi', 'Xiaomi'), ('Realme', 'Realme'), ('Motorola', 'Motorola'), ('Sony', 'Sony'), ('LG', 'LG'), ('HP', 'HP'), ('Dell', 'Dell'), ('Lenovo', 'Lenovo'), ('Asus', 'Asus'), ('Acer', 'Acer'), ('MSI', 'MSI'), ('Canon', 'Canon'), ('Nikon', 'Nikon'), ('Boat', 'Boat'), ('JBL', 'JBL'), ('Philips', 'Philips'), ('Amazon', 'Amazon'), ('Google', 'Google'), ('Nothing', 'Nothing'), ('Fire-Boltt', 'Fire-Boltt'), ('Noise', 'Noise'), ('RealWear', 'RealWear'), ('DJI', 'DJI')], default='Sony', max_length=100),
        ),
    ]
