# Generated by Django 5.2.1 on 2025-06-15 10:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_order_user_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(choices=[('Apple', 'Apple'), ('Samsung', 'Samsung'), ('OnePlus', 'OnePlus'), ('Xiaomi', 'Xiaomi'), ('Realme', 'Realme'), ('Motorola', 'Motorola'), ('Sony', 'Sony'), ('LG', 'LG'), ('HP', 'HP'), ('Dell', 'Dell'), ('Lenovo', 'Lenovo'), ('Asus', 'Asus'), ('Acer', 'Acer'), ('MSI', 'MSI'), ('Canon', 'Canon'), ('Nikon', 'Nikon'), ('Boat', 'Boat'), ('JBL', 'JBL'), ('Philips', 'Philips'), ('Panasonic', 'Panasonic'), ('Amazon', 'Amazon'), ('Google', 'Google'), ('Nothing', 'Nothing'), ('Fire-Boltt', 'Fire-Boltt'), ('Noise', 'Noise'), ('RealWear', 'RealWear'), ('DJI', 'DJI'), ('Fitbit', 'Fitbit'), ('Garmin', 'Garmin'), ('Haier', 'Haier'), ('Logitech', 'Logitech'), ('Prestige', 'Prestige'), ('Morphy Richards', 'Morphy Richards'), ('TCL', 'TCL'), ('Amazfit', 'Amazfit'), ('Sennheiser', 'Sennheiser'), ('GoPro', 'GoPro'), ('Fujifilm', 'Fujifilm'), ('Insta360', 'Insta360'), ('Wipro', 'Wipro'), ('Epson', 'Epson')], default='Sony', max_length=100),
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'product')},
            },
        ),
    ]
